openapi: 3.0.3
info:
  title: Social network for travelers
  description: |-
    API for a social network for travelers
  contact:
    email: 735007@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: https://snft.net/api/v3
tags:
  - name: posts
    description: Everything about your posts
  - name: comments
    description: Everything about your comments
  - name: user
    description: User
paths:
  /posts:
    put:
      tags:
        - posts
      summary: Update an existing posts
      description: Update an existing posts by Id
      operationId: updateposts
      security:
        - postsstore_auth:
            - write:postss
            - read:postss
    post:
      tags:
        - posts
      summary: Add a new posts to the store
      description: Add a new posts to the store
      operationId: addposts
      security:
        - postsstore_auth:
            - write:postss
            - read:postss
  /posts/findByStatus:
    get:
      tags:
        - posts
      summary: Finds postss by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findpostssByStatus
      security:
        - postsstore_auth:
            - write:postss
            - read:postss
  /posts/findByTags:
    get:
      tags:
        - posts
      summary: Finds postss by tags
      description: Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
      operationId: findpostssByTags
      security:
        - postsstore_auth:
            - write:postss
            - read:postss
  /posts/{postsId}:
    get:
      tags:
        - posts
      summary: Find posts by ID
      description: Returns a single posts
      operationId: getpostsById
      security:
        - api_key: []
        - postsstore_auth:
            - write:postss
            - read:postss
    post:
      tags:
        - posts
      summary: Updates a posts in the store with form data
      description: ''
      operationId: updatepostsWithForm
      security:
        - postsstore_auth:
            - write:postss
            - read:postss
    delete:
      tags:
        - posts
      summary: Deletes a posts
      description: delete a posts
      operationId: deleteposts
      security:
        - postsstore_auth:
            - write:postss
            - read:postss
  /posts/{postsId}/uploadImage:
    post:
      tags:
        - posts
      summary: uploads an image
      description: ''
      operationId: uploadFile
      security:
        - postsstore_auth:
            - write:postss
            - read:postss
  /comments:
    put:
      tags:
        - comments
      summary: Update an existing comments
      description: Update an existing comments by Id
      operationId: updatecomments
      security:
        - commentsstore_auth:
            - write:commentss
            - read:commentss
    post:
      tags:
        - comments
      summary: Add a new comments to the store
      description: Add a new comments to the store
      operationId: addcomments
      security:
        - commentsstore_auth:
            - write:commentss
            - read:commentss
  /comments/findByStatus:
    get:
      tags:
        - comments
      summary: Finds commentss by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findcommentssByStatus
      security:
        - commentsstore_auth:
            - write:commentss
            - read:commentss
  /comments/findByTags:
    get:
      tags:
        - comments
      summary: Finds commentss by tags
      description: Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
      operationId: findcommentssByTags
      security:
        - commentsstore_auth:
            - write:commentss
            - read:commentss
  /comments/{commentsId}:
    get:
      tags:
        - comments
      summary: Find comments by ID
      description: Returns a single comments
      operationId: getcommentsById
      security:
        - api_key: []
        - commentsstore_auth:
            - write:commentss
            - read:commentss
    post:
      tags:
        - comments
      summary: Updates a comments in the store with form data
      description: ''
      operationId: updatecommentsWithForm
      security:
        - commentsstore_auth:
            - write:commentss
            - read:commentss
    delete:
      tags:
        - comments
      summary: Deletes a comments
      description: delete a comments
      operationId: deletecomments
      security:
        - commentsstore_auth:
            - write:commentss
            - read:commentss
  /comments/{commentsId}/uploadImage:
    post:
      tags:
        - comments
      summary: uploads an image
      description: ''
      operationId: uploadFile2
      security:
        - commentsstore_auth:
            - write:commentss
            - read:commentss
  /user:
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
  /user/createWithList:
    post:
      tags:
        - user
      summary: Creates list of users with given input array
      description: Creates list of users with given input array
      operationId: createUsersWithListInput
  /user/login:
    get:
      tags:
        - user
      summary: Logs user into the system
      description: ''
      operationId: loginUser
  /user/logout:
    get:
      tags:
        - user
      summary: Logs out current logged in user session
      description: ''
      operationId: logoutUser
  /user/{username}:
    get:
      tags:
        - user
      summary: Get user by user name
      description: ''
      operationId: getUserByName
    put:
      tags:
        - user
      summary: Update user
      description: This can only be done by the logged in user.
      operationId: updateUser
    delete:
      tags:
        - user
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: deleteUser
components:
  securitySchemes:
    postsstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://postsstore3.swagger.io/oauth/authorize
          scopes:
            write:postss: modify postss in your account
            read:postss: read your postss
    commentsstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://postsstore3.swagger.io/oauth/authorize
          scopes:
            write:postss: modify commentss in your account
            read:postss: read your commentss
    api_key:
      type: apiKey
      name: api_key
      in: header